### ISSUE TITLE
Thoughts on sendToQueue vs publish method

### ISSUE THREAD

**Issue by itsJess1ca** [swimlane/coconspirators#2]
Hi,
First off, this looks amazing.
I was just reading through the src and was curious as to the decision behind using the `sendToQueue()` method instead of the `publish()` method. 

My team uses routing a bunch and therefore I cannot use `sendToQueue` as it's there to abstract the routing configs away.

Really just curious on thoughts, if it was a design decision or overlooked etc.
Or perhaps I'm simply missing something :D

**Comment by amcdnl** [comment]
I haven't really dug into exchanges very much yet, so its more out of my ignorance. 

I suppose I should rename that to be more consistent though.

I need to spend some time on making exchanges work natively. Its on my list for in the next 2 weeks though. Happy to accept PRs or thoughts!

**Comment by itsJess1ca** [comment]
Awesome :+1:
This project definitely interests me as I'm using rabbit heavily lately, and who doesn't love typescript ;)

If I get time this weekend I'll look into a PR for publish vs sendToQueue - I noticed some other bits too, like the `prefetch` param in the `subscribeOptions` is never actually used - will have a PR in for that shortly.

**Comment by amcdnl** [comment]
that would be awesome!
